function h = putFigureLabel(s, pos, sz)
% function h = putFigureLabel(s, [pos=[0.025 0.975 0.3 0.025]], [sz=12])

if nargin < 2 || isempty(pos);  pos = [0.025 0.975 0.3 0.025];  end
if nargin < 3 || isempty(sz);   sz  = 10;  end

h = uicontrol('Style', 'text',...
       'String', s,... %replace something with the text you want
       'Units','normalized',...
       'Position', pos,...
       'FontSize',sz,...
       'BackgroundColor', 'w',...
       'HorizontalAlignment', 'left'); 